#Based off tutorial
#https://medium.com/android-bits/android-app-from-scratch-part-5-continuous-integration-with-travis-ci-1a6d30d22822
#https://www.travis-ci.org/codecov/example-android/jobs/490283689/config

language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - platform-tools
    - tools

    - build-tools-27.0.3

    - android-27

    - extra
    - addon

    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-19

    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"


before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 100M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  
script:
  #- ./gradlew build jacocoTestReport assembleAndroidTest

  #- adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  #- ./gradlew connectedCheck
  - ./gradlew test
  - ./gradlew connectedAndroidTest --stacktrace --info